### ISSUE TITLE
Create reana.yml file

### ISSUE THREAD

**Issue by Samcoodess** [Samcoodess/reana-dms#6]
Hello mentors, 
I read the "Structure your analysis" part on REANA. I have reana.yaml file but it's throwing an error while I create a new workflow. 
Error ====> Cannot create a workflow

**Comment by matthewfeickert** [comment]
> have reana.yaml file but it's throwing an error while I create a new workflow.
Error ====> Cannot create a workflow

@Samcoodess Please link to the commit of the `reana.yaml` that you're using here, or paste it here with formatting. To be able to give input on things the code is necessary.

**Comment by Samcoodess** [comment]
Hello @matthewfeickert , 
I have linked the reana.yaml  file committed to another repo "RCFM". I listed all the files in the format given in the documentation on REANA's website. To organize it better, I separated it with comments. It's still a demo format thus, I have commented out most parts. 
Q. Am I supposed to list every .dat, .pyc, .csv, .ipynb, . py files like this?

REANA.YAML - [reana.yaml](https://github.com/Samcoodess/RCFM/blob/create_reana.yaml/reana.yaml)

**Comment by Samcoodess** [comment]
Hello, I hope you are doing well.  @matthewfeickert  Could you review my reana.yaml file once? The previous one had all the paths of the file copied but now, I tried storing everything in the directory. However, When trying to validate this using `reana-client validate`. It throws an error.
 | ==> ERROR: Something went wrong when trying to validate /Users/sambridhideo/dev/RCFM/reana.yaml


Could you connect me with someone who has worked with creating reana.yaml for the model containing many inputs and outputs ? The examples and the documentation don't explicitly have a guide for many files. 

This is my draft currently ! _________________________________________________________________________________________________________
```
version: 0.9.1

inputs:
  files:
    - DataAid.py
    - DataImporter.py
    - Neros.py
    - Neros_test.py
    - rotCurve.py

  directories:
    - data_csv_files:  #contains all the .csv files
    - data_dat_files:  # Contains .dat Files used as input to model.ipynb
    - data_txt_files:  # .txt files
    - graphs:          # contains generated graphs output of model.ipynb
    - plots:           # contains few plots outputs of model.ipynb

environment:
  name: rcfm-env  

workflow:
  - name: data_import
    type: serial
    environment:
      name: rcfm-env
    commands:
      - python DataImporter.py
    inputs:
      - name: data_csv_files
      - name: data_dat_files
      - name: data_txt_files
    outputs:
      - name: imported_data

  - name: data_processing
    type: serial
    environment:
      name: rcfm-env
    commands:
      - jupyter nbconvert --execute --to notebook --inplace model.ipynb
    inputs:
      - name: imported_data
      - name: DataAid.py
      - name: Neros.py
      - name: Neros_test.py
      - name: rotCurve.py
    outputs:
      - name: analysis_results

  - name: generate_plots
    type: serial
    environment:
      name: rcfm-env
    commands:
      - jupyter nbconvert --execute --to notebook --inplace model.ipynb
    inputs:
      - name: analysis_results
    outputs:
      - name: plots
      - name: graphs
```

**Comment by kratsg** [comment]
The main issue is that `workflow` is a dicitonary, not a list of dictionaries. The list of dictionaries is under `workflow.specification.steps` I believe. There's also some other issues which I went ahead and quickly fixed so this passes validation

```
version: 0.9.1

inputs:
  files:
    - DataAid.py
    - DataImporter.py
    - Neros.py
    - Neros_test.py
    - rotCurve.py

  directories:
    - data_csv_files  #contains all the .csv files
    - data_dat_files  # Contains .dat Files used as input to model.ipynb
    - data_txt_files  # .txt files
    - graphs          # contains generated graphs output of model.ipynb
    - plots           # contains few plots outputs of model.ipynb

environment:
  name: rcfm-env

workflow:
  type: serial
  specification:
    steps:
      - name: data_import
        environment: rcfm-env
        commands:
          - python DataImporter.py
        inputs:
          - data_csv_files
          - data_dat_files
          - data_txt_files
        outputs:
          - name: imported_data

      - name: data_processing
        environment: rcfm-env
        commands:
          - jupyter nbconvert --execute --to notebook --inplace model.ipynb
        inputs:
          - name: imported_data
          - name: DataAid.py
          - name: Neros.py
          - name: Neros_test.py
          - name: rotCurve.py
        outputs:
          - name: analysis_results

      - name: generate_plots
        environment: rcfm-env
        commands:
          - jupyter nbconvert --execute --to notebook --inplace model.ipynb
        inputs:
          - name: analysis_results
        outputs:
          - name: plots
          - name: graphs
```
